// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: employee.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPersonnel = `-- name: CountPersonnel :one
select count(*)::bigint as total
from employees e
join
    employee_details ed
    on ed.employee_id = e.id
    and ed.is_employee_details_new is true
    and ed.language_code = $1
where
    exists (select 1 from employee_socials es where es.employee_id = e.id)
    and e.highest_academic_degree is not null
    and e.speciality is not null
    and e.current_workplace is not null
    and (nullif($2::text, '') is null or e.unique_id = $2)
    and (
        nullif($3::text, '') is null
        or ed.name ilike '%' || $3 || '%'
    )
    and (
        nullif($4::text, '') is null
        or ed.surname ilike '%' || $4 || '%'
    )
    and (
        nullif($5::text, '') is null
        or ed.middlename ilike '%' || $5 || '%'
    )
    and (
        nullif($6::text, '') is null
        or e.current_workplace = $6
    )
    and (
        nullif($7::text, '') is null
        or e.highest_academic_degree = $7
    )
`

type CountPersonnelParams struct {
	LanguageCode   string `json:"language_code"`
	Uid            string `json:"uid"`
	Name           string `json:"name"`
	Surname        string `json:"surname"`
	Middlename     string `json:"middlename"`
	Workplace      string `json:"workplace"`
	AcademicDegree string `json:"academic_degree"`
}

func (q *Queries) CountPersonnel(ctx context.Context, arg CountPersonnelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPersonnel,
		arg.LanguageCode,
		arg.Uid,
		arg.Name,
		arg.Surname,
		arg.Middlename,
		arg.Workplace,
		arg.AcademicDegree,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
  unique_id,
  user_id,
  gender,
  tin
) VALUES(
  $1, $2, $3, $4
) RETURNING id, created_at, updated_at
`

type CreateEmployeeParams struct {
	UniqueID string      `json:"unique_id"`
	UserID   pgtype.Int8 `json:"user_id"`
	Gender   pgtype.Text `json:"gender"`
	Tin      pgtype.Text `json:"tin"`
}

type CreateEmployeeRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (CreateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.UniqueID,
		arg.UserID,
		arg.Gender,
		arg.Tin,
	)
	var i CreateEmployeeRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
delete from employees
where id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
select id, unique_id, created_at, updated_at, user_id, gender, tin, highest_academic_degree, speciality, current_workplace
from employees
where id = $1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Gender,
		&i.Tin,
		&i.HighestAcademicDegree,
		&i.Speciality,
		&i.CurrentWorkplace,
	)
	return i, err
}

const getEmployeeByUniqueIdentifier = `-- name: GetEmployeeByUniqueIdentifier :one
select id, unique_id, created_at, updated_at, user_id, gender, tin, highest_academic_degree, speciality, current_workplace
from employees
where unique_id = $1
`

func (q *Queries) GetEmployeeByUniqueIdentifier(ctx context.Context, uniqueID string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUniqueIdentifier, uniqueID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Gender,
		&i.Tin,
		&i.HighestAcademicDegree,
		&i.Speciality,
		&i.CurrentWorkplace,
	)
	return i, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
select id, unique_id, created_at, updated_at, user_id, gender, tin, highest_academic_degree, speciality, current_workplace
from employees
where user_id = $1
`

func (q *Queries) GetEmployeeByUserID(ctx context.Context, userID pgtype.Int8) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUserID, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Gender,
		&i.Tin,
		&i.HighestAcademicDegree,
		&i.Speciality,
		&i.CurrentWorkplace,
	)
	return i, err
}

const getPersonnelPaginated = `-- name: GetPersonnelPaginated :many
select
    e.id,
    e.unique_id,
    e.gender,
    e.tin,
    e.highest_academic_degree,
    e.speciality,
    e.current_workplace,
    ed.surname,
    ed.name,
    ed.middlename
from employees e
join
    employee_details ed
    on ed.employee_id = e.id
    and ed.is_employee_details_new is true
    and ed.language_code = $1
where
    -- must exist in employee_socials
    exists (select 1 from employee_socials es where es.employee_id = e.id)
    -- required non-null denormalized fields
    and e.highest_academic_degree is not null
    and e.speciality is not null
    and e.current_workplace is not null

    -- optional filters (pass NULL to ignore)
    and (nullif($2::text, '') is null or e.unique_id = $2)
    and (
        nullif($3::text, '') is null
        or ed.name ilike '%' || $3 || '%'
    )
    and (
        nullif($4::text, '') is null
        or ed.surname ilike '%' || $4 || '%'
    )
    and (
        nullif($5::text, '') is null
        or ed.middlename ilike '%' || $5 || '%'
    )
    and (
        nullif($6::text, '') is null
        or e.current_workplace = $6
    )
    and (
        nullif($7::text, '') is null
        or e.highest_academic_degree = $7
    )
order by e.id
limit $9
offset $8
`

type GetPersonnelPaginatedParams struct {
	LanguageCode   string `json:"language_code"`
	Uid            string `json:"uid"`
	Name           string `json:"name"`
	Surname        string `json:"surname"`
	Middlename     string `json:"middlename"`
	Workplace      string `json:"workplace"`
	AcademicDegree string `json:"academic_degree"`
	Page           int32  `json:"page"`
	Limit          int32  `json:"limit"`
}

type GetPersonnelPaginatedRow struct {
	ID                    int64       `json:"id"`
	UniqueID              string      `json:"unique_id"`
	Gender                pgtype.Text `json:"gender"`
	Tin                   pgtype.Text `json:"tin"`
	HighestAcademicDegree pgtype.Text `json:"highest_academic_degree"`
	Speciality            pgtype.Text `json:"speciality"`
	CurrentWorkplace      pgtype.Text `json:"current_workplace"`
	Surname               string      `json:"surname"`
	Name                  string      `json:"name"`
	Middlename            pgtype.Text `json:"middlename"`
}

func (q *Queries) GetPersonnelPaginated(ctx context.Context, arg GetPersonnelPaginatedParams) ([]GetPersonnelPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getPersonnelPaginated,
		arg.LanguageCode,
		arg.Uid,
		arg.Name,
		arg.Surname,
		arg.Middlename,
		arg.Workplace,
		arg.AcademicDegree,
		arg.Page,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPersonnelPaginatedRow{}
	for rows.Next() {
		var i GetPersonnelPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UniqueID,
			&i.Gender,
			&i.Tin,
			&i.HighestAcademicDegree,
			&i.Speciality,
			&i.CurrentWorkplace,
			&i.Surname,
			&i.Name,
			&i.Middlename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueHighestAcademicDegrees = `-- name: ListUniqueHighestAcademicDegrees :many
select distinct e.highest_academic_degree
from employees e
where
    e.highest_academic_degree is not null
    and e.highest_academic_degree <> ''
order by e.highest_academic_degree asc
`

func (q *Queries) ListUniqueHighestAcademicDegrees(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listUniqueHighestAcademicDegrees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var highest_academic_degree pgtype.Text
		if err := rows.Scan(&highest_academic_degree); err != nil {
			return nil, err
		}
		items = append(items, highest_academic_degree)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueWorkplaces = `-- name: ListUniqueWorkplaces :many
select distinct e.current_workplace
from employees e
join
    employee_details ed
    on ed.employee_id = e.id
    and ed.is_employee_details_new is true
    and ed.language_code = $1
where
    exists (select 1 from employee_socials es where es.employee_id = e.id)
    and e.highest_academic_degree is not null
    and e.speciality is not null
    and e.current_workplace is not null
    and e.current_workplace <> ''
order by e.current_workplace asc
`

func (q *Queries) ListUniqueWorkplaces(ctx context.Context, languageCode string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listUniqueWorkplaces, languageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var current_workplace pgtype.Text
		if err := rows.Scan(&current_workplace); err != nil {
			return nil, err
		}
		items = append(items, current_workplace)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
