// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: employee.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPersonnel = `-- name: CountPersonnel :one
SELECT 
	COUNT(*)
FROM 
	employees	
WHERE
	($1::text IS NULL or employees.unique_id = $1)
	AND EXISTS (
		SELECT 1
		FROM employee_details
		WHERE 
			employee_details.language_code = $2
			and employee_details.is_employee_details_new = True
		  AND ($3::text IS NULL OR employee_details.name = $3)
		 	AND ($4::text IS NULL OR employee_details.surname = $4)
		  AND ($5::text IS NULL OR employee_details.middlename = $5)		
	  )
  	AND EXISTS (
  		SELECT 1
  		FROM employee_degrees
  		WHERE 
  			employee_degrees.employee_id = employees.id
  			and employee_degrees.language_code = $2
  			and ($6::text IS NULL OR employee_degrees.speciality = $6)
  	)
  	AND EXISTS (
  		SELECT 1
  		FROM employee_work_experiences
  		WHERE 
  			employee_work_experiences.employee_id = employees.id
  			AND employee_work_experiences.language_code = $2
  	)
`

type CountPersonnelParams struct {
	Uid          pgtype.Text `json:"uid"`
	LanguageCode string      `json:"language_code"`
	Name         pgtype.Text `json:"name"`
	Surname      pgtype.Text `json:"surname"`
	Middlename   pgtype.Text `json:"middlename"`
	Speciality   pgtype.Text `json:"speciality"`
}

func (q *Queries) CountPersonnel(ctx context.Context, arg CountPersonnelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPersonnel,
		arg.Uid,
		arg.LanguageCode,
		arg.Name,
		arg.Surname,
		arg.Middlename,
		arg.Speciality,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
  unique_id
) VALUES(
  $1  
) RETURNING id, created_at, updated_at
`

type CreateEmployeeRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmployee(ctx context.Context, uniqueID string) (CreateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, createEmployee, uniqueID)
	var i CreateEmployeeRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees 
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, unique_id, created_at, updated_at
FROM employees
WHERE id = $1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByUniqueIdentifier = `-- name: GetEmployeeByUniqueIdentifier :one
SELECT id, unique_id, created_at, updated_at
FROM employees
WHERE unique_id = $1
`

func (q *Queries) GetEmployeeByUniqueIdentifier(ctx context.Context, uniqueID string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUniqueIdentifier, uniqueID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonnelPaginated = `-- name: GetPersonnelPaginated :many
SELECT 
	employees.id,
	employees.unique_id
FROM 
	employees	
WHERE
	($1::text IS NULL or employees.unique_id = $1)
	AND EXISTS (
		SELECT 1
		FROM employee_details
		WHERE 
			employee_details.language_code = $2
			and employee_details.is_employee_details_new = True
		  AND ($3::text IS NULL OR employee_details.name = $3)
		 	AND ($4::text IS NULL OR employee_details.surname = $4)
		  AND ($5::text IS NULL OR employee_details.middlename = $5)		
	  )
  	AND EXISTS (
  		SELECT 1
  		FROM employee_degrees
  		WHERE 
  			employee_degrees.employee_id = employees.id
  			and employee_degrees.language_code = $2
  			and ($6::text IS NULL OR employee_degrees.speciality = $6)
  	)
  	AND EXISTS (
  		SELECT 1
  		FROM employee_work_experiences
  		WHERE 
  			employee_work_experiences.employee_id = employees.id
  			AND employee_work_experiences.language_code = $2
  	)
ORDER BY 
	employees.id,
	employees.unique_id
LIMIT $8
OFFSET $7
`

type GetPersonnelPaginatedParams struct {
	Uid          pgtype.Text `json:"uid"`
	LanguageCode string      `json:"language_code"`
	Name         pgtype.Text `json:"name"`
	Surname      pgtype.Text `json:"surname"`
	Middlename   pgtype.Text `json:"middlename"`
	Speciality   pgtype.Text `json:"speciality"`
	Page         int32       `json:"page"`
	Limit        int32       `json:"limit"`
}

type GetPersonnelPaginatedRow struct {
	ID       int64  `json:"id"`
	UniqueID string `json:"unique_id"`
}

func (q *Queries) GetPersonnelPaginated(ctx context.Context, arg GetPersonnelPaginatedParams) ([]GetPersonnelPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getPersonnelPaginated,
		arg.Uid,
		arg.LanguageCode,
		arg.Name,
		arg.Surname,
		arg.Middlename,
		arg.Speciality,
		arg.Page,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPersonnelPaginatedRow{}
	for rows.Next() {
		var i GetPersonnelPaginatedRow
		if err := rows.Scan(&i.ID, &i.UniqueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
